# Generated by Django 4.2.11 on 2025-12-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Todo', 'verbose_name_plural': 'Todos'},
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['-created_at'], name='todos_created_9ed8f2_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['is_done'], name='todos_is_done_b151ce_idx'),
        ),
        migrations.AlterModelTable(
            name='todo',
            table='todos',
        ),
    ]
